version: '3'
services:
  db:
    image: postgres:14.10
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    
  
  
