version: '3'
services:
  db:
    image: postgres:14.10
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
  
  app:
    build: 
      context: .
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  db:
  
  